// Mocks generated by Mockito 5.4.4 from annotations
// in online_exam/test/features/auth/domain/use_cases/forgot_password_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:online_exam/core/networking/common/api_result.dart' as _i4;
import 'package:online_exam/features/auth/data/models/request/ForgetPasswordRequest.dart'
    as _i6;
import 'package:online_exam/features/auth/data/models/request/RegisterRequest.dart'
    as _i13;
import 'package:online_exam/features/auth/data/models/request/ResetPasswordRequest.dart'
    as _i11;
import 'package:online_exam/features/auth/data/models/request/SignInRequest.dart'
    as _i12;
import 'package:online_exam/features/auth/data/models/request/VerifyResetCodeRequest.dart'
    as _i9;
import 'package:online_exam/features/auth/data/models/response/AuthResponse.dart'
    as _i10;
import 'package:online_exam/features/auth/data/models/response/ForgotPasswordResponse.dart'
    as _i5;
import 'package:online_exam/features/auth/data/models/response/VerifyResetCodeResponse.dart'
    as _i8;
import 'package:online_exam/features/auth/domain/repositories/auth_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i2.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ApiResult<_i5.ForgotPasswordResponse>> forgotPassword(
          _i6.ForgetPasswordRequest? body) =>
      (super.noSuchMethod(
        Invocation.method(
          #forgotPassword,
          [body],
        ),
        returnValue:
            _i3.Future<_i4.ApiResult<_i5.ForgotPasswordResponse>>.value(
                _i7.dummyValue<_i4.ApiResult<_i5.ForgotPasswordResponse>>(
          this,
          Invocation.method(
            #forgotPassword,
            [body],
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<_i5.ForgotPasswordResponse>>);

  @override
  _i3.Future<_i4.ApiResult<_i8.VerifyResetCodeResponse>> verifyResetCode(
          _i9.VerifyResetCodeRequest? body) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyResetCode,
          [body],
        ),
        returnValue:
            _i3.Future<_i4.ApiResult<_i8.VerifyResetCodeResponse>>.value(
                _i7.dummyValue<_i4.ApiResult<_i8.VerifyResetCodeResponse>>(
          this,
          Invocation.method(
            #verifyResetCode,
            [body],
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<_i8.VerifyResetCodeResponse>>);

  @override
  _i3.Future<_i4.ApiResult<_i10.AuthResponse>> resetPassword(
          _i11.ResetPasswordRequest? body) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [body],
        ),
        returnValue: _i3.Future<_i4.ApiResult<_i10.AuthResponse>>.value(
            _i7.dummyValue<_i4.ApiResult<_i10.AuthResponse>>(
          this,
          Invocation.method(
            #resetPassword,
            [body],
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<_i10.AuthResponse>>);

  @override
  _i3.Future<_i4.ApiResult<_i10.AuthResponse>> login(
          _i12.SignInRequest? body) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [body],
        ),
        returnValue: _i3.Future<_i4.ApiResult<_i10.AuthResponse>>.value(
            _i7.dummyValue<_i4.ApiResult<_i10.AuthResponse>>(
          this,
          Invocation.method(
            #login,
            [body],
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<_i10.AuthResponse>>);

  @override
  _i3.Future<_i4.ApiResult<_i10.AuthResponse>> signeUp(
          _i13.RegisterRequest? body) =>
      (super.noSuchMethod(
        Invocation.method(
          #signeUp,
          [body],
        ),
        returnValue: _i3.Future<_i4.ApiResult<_i10.AuthResponse>>.value(
            _i7.dummyValue<_i4.ApiResult<_i10.AuthResponse>>(
          this,
          Invocation.method(
            #signeUp,
            [body],
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<_i10.AuthResponse>>);
}
