// Mocks generated by Mockito 5.4.4 from annotations
// in online_exam/test/features/auth/presentation/forget_password/ViewModel/forget_password_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:online_exam/core/networking/common/api_result.dart' as _i5;
import 'package:online_exam/features/auth/data/models/request/ForgetPasswordRequest.dart'
    as _i7;
import 'package:online_exam/features/auth/data/models/request/ResetPasswordRequest.dart'
    as _i14;
import 'package:online_exam/features/auth/data/models/request/VerifyResetCodeRequest.dart'
    as _i11;
import 'package:online_exam/features/auth/data/models/response/auth_response_model.dart'
    as _i13;
import 'package:online_exam/features/auth/data/models/response/ForgotPasswordResponse.dart'
    as _i6;
import 'package:online_exam/features/auth/data/models/response/VerifyResetCodeResponse.dart'
    as _i10;
import 'package:online_exam/features/auth/domain/repositories/auth_repository.dart'
    as _i2;
import 'package:online_exam/features/auth/domain/use_cases/forgot_password_use_case.dart'
    as _i3;
import 'package:online_exam/features/auth/domain/use_cases/reset_password_use_case.dart'
    as _i12;
import 'package:online_exam/features/auth/domain/use_cases/verify_reset_code_use_case.dart'
    as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthRepository_0 extends _i1.SmartFake
    implements _i2.AuthRepository {
  _FakeAuthRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ForgotPasswordUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockForgotPasswordUseCase extends _i1.Mock
    implements _i3.ForgotPasswordUseCase {
  MockForgotPasswordUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthRepository get authRepository => (super.noSuchMethod(
        Invocation.getter(#authRepository),
        returnValue: _FakeAuthRepository_0(
          this,
          Invocation.getter(#authRepository),
        ),
      ) as _i2.AuthRepository);

  @override
  set authRepository(_i2.AuthRepository? _authRepository) => super.noSuchMethod(
        Invocation.setter(
          #authRepository,
          _authRepository,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<_i5.DataResult<_i6.ForgotPasswordResponse>> call(
          _i7.ForgetPasswordRequest? body) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [body],
        ),
        returnValue:
            _i4.Future<_i5.DataResult<_i6.ForgotPasswordResponse>>.value(
                _i8.dummyValue<_i5.DataResult<_i6.ForgotPasswordResponse>>(
          this,
          Invocation.method(
            #call,
            [body],
          ),
        )),
      ) as _i4.Future<_i5.DataResult<_i6.ForgotPasswordResponse>>);
}

/// A class which mocks [VerifyResetCodeUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockVerifyResetCodeUseCase extends _i1.Mock
    implements _i9.VerifyResetCodeUseCase {
  MockVerifyResetCodeUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthRepository get authRepository => (super.noSuchMethod(
        Invocation.getter(#authRepository),
        returnValue: _FakeAuthRepository_0(
          this,
          Invocation.getter(#authRepository),
        ),
      ) as _i2.AuthRepository);

  @override
  set authRepository(_i2.AuthRepository? _authRepository) => super.noSuchMethod(
        Invocation.setter(
          #authRepository,
          _authRepository,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<_i5.DataResult<_i10.VerifyResetCodeResponse>> call(
          _i11.VerifyResetCodeRequest? body) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [body],
        ),
        returnValue:
            _i4.Future<_i5.DataResult<_i10.VerifyResetCodeResponse>>.value(
                _i8.dummyValue<_i5.DataResult<_i10.VerifyResetCodeResponse>>(
          this,
          Invocation.method(
            #call,
            [body],
          ),
        )),
      ) as _i4.Future<_i5.DataResult<_i10.VerifyResetCodeResponse>>);
}

/// A class which mocks [ResetPasswordUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockResetPasswordUseCase extends _i1.Mock
    implements _i12.ResetPasswordUseCase {
  MockResetPasswordUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthRepository get authRepository => (super.noSuchMethod(
        Invocation.getter(#authRepository),
        returnValue: _FakeAuthRepository_0(
          this,
          Invocation.getter(#authRepository),
        ),
      ) as _i2.AuthRepository);

  @override
  set authRepository(_i2.AuthRepository? _authRepository) => super.noSuchMethod(
        Invocation.setter(
          #authRepository,
          _authRepository,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<_i5.DataResult<_i13.AuthResponse>> call(
          _i14.ResetPasswordRequest? body) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [body],
        ),
        returnValue: _i4.Future<_i5.DataResult<_i13.AuthResponse>>.value(
            _i8.dummyValue<_i5.DataResult<_i13.AuthResponse>>(
          this,
          Invocation.method(
            #call,
            [body],
          ),
        )),
      ) as _i4.Future<_i5.DataResult<_i13.AuthResponse>>);
}
