// Mocks generated by Mockito 5.4.4 from annotations
// in online_exam/test/features/survey/data/data_sources/remote_data_source/survey_api_remote_data_source_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;

import 'package:mockito/mockito.dart' as _i1;
import 'package:online_exam/core/networking/api/api_manager.dart' as _i8;
import 'package:online_exam/features/auth/data/models/request/change_password_request.dart'
    as _i16;
import 'package:online_exam/features/auth/data/models/request/ForgetPasswordRequest.dart'
    as _i10;
import 'package:online_exam/features/auth/data/models/request/RegisterRequest.dart'
    as _i14;
import 'package:online_exam/features/auth/data/models/request/ResetPasswordRequest.dart'
    as _i12;
import 'package:online_exam/features/auth/data/models/request/SignInRequest.dart'
    as _i13;
import 'package:online_exam/features/auth/data/models/request/user_request.dart'
    as _i15;
import 'package:online_exam/features/auth/data/models/request/VerifyResetCodeRequest.dart'
    as _i11;
import 'package:online_exam/features/auth/data/models/response/auth_response_model.dart'
    as _i4;
import 'package:online_exam/features/auth/data/models/response/ForgotPasswordResponse.dart'
    as _i2;
import 'package:online_exam/features/auth/data/models/response/VerifyResetCodeResponse.dart'
    as _i3;
import 'package:online_exam/features/exam/data/models/response/exam_response_model.dart'
    as _i5;
import 'package:online_exam/features/questions/data/models/online/question_response_model.dart'
    as _i7;
import 'package:online_exam/features/survey/data/models/subject_response_model.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeForgotPasswordResponse_0 extends _i1.SmartFake
    implements _i2.ForgotPasswordResponse {
  _FakeForgotPasswordResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVerifyResetCodeResponse_1 extends _i1.SmartFake
    implements _i3.VerifyResetCodeResponse {
  _FakeVerifyResetCodeResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuthResponse_2 extends _i1.SmartFake implements _i4.AuthResponse {
  _FakeAuthResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeExamResponseModel_3 extends _i1.SmartFake
    implements _i5.ExamResponseModel {
  _FakeExamResponseModel_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSubjectResponseModel_4 extends _i1.SmartFake
    implements _i6.SubjectResponseModel {
  _FakeSubjectResponseModel_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeQuestionResponseModel_5 extends _i1.SmartFake
    implements _i7.QuestionResponseModel {
  _FakeQuestionResponseModel_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiManager extends _i1.Mock implements _i8.ApiManager {
  MockApiManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i2.ForgotPasswordResponse> forgotPassword(
          _i10.ForgetPasswordRequest? body) =>
      (super.noSuchMethod(
        Invocation.method(
          #forgotPassword,
          [body],
        ),
        returnValue: _i9.Future<_i2.ForgotPasswordResponse>.value(
            _FakeForgotPasswordResponse_0(
          this,
          Invocation.method(
            #forgotPassword,
            [body],
          ),
        )),
      ) as _i9.Future<_i2.ForgotPasswordResponse>);

  @override
  _i9.Future<_i3.VerifyResetCodeResponse> verifyResetCode(
          _i11.VerifyResetCodeRequest? body) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyResetCode,
          [body],
        ),
        returnValue: _i9.Future<_i3.VerifyResetCodeResponse>.value(
            _FakeVerifyResetCodeResponse_1(
          this,
          Invocation.method(
            #verifyResetCode,
            [body],
          ),
        )),
      ) as _i9.Future<_i3.VerifyResetCodeResponse>);

  @override
  _i9.Future<_i4.AuthResponse> resetPassword(_i12.ResetPasswordRequest? body) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [body],
        ),
        returnValue: _i9.Future<_i4.AuthResponse>.value(_FakeAuthResponse_2(
          this,
          Invocation.method(
            #resetPassword,
            [body],
          ),
        )),
      ) as _i9.Future<_i4.AuthResponse>);

  @override
  _i9.Future<_i4.AuthResponse> signIn(_i13.SignInRequest? user) =>
      (super.noSuchMethod(
        Invocation.method(
          #signIn,
          [user],
        ),
        returnValue: _i9.Future<_i4.AuthResponse>.value(_FakeAuthResponse_2(
          this,
          Invocation.method(
            #signIn,
            [user],
          ),
        )),
      ) as _i9.Future<_i4.AuthResponse>);

  @override
  _i9.Future<_i4.AuthResponse> signUp(_i14.RegisterRequest? user) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUp,
          [user],
        ),
        returnValue: _i9.Future<_i4.AuthResponse>.value(_FakeAuthResponse_2(
          this,
          Invocation.method(
            #signUp,
            [user],
          ),
        )),
      ) as _i9.Future<_i4.AuthResponse>);

  @override
  _i9.Future<_i5.ExamResponseModel> getExamsBySubjectId(String? subjectId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getExamsBySubjectId,
          [subjectId],
        ),
        returnValue:
            _i9.Future<_i5.ExamResponseModel>.value(_FakeExamResponseModel_3(
          this,
          Invocation.method(
            #getExamsBySubjectId,
            [subjectId],
          ),
        )),
      ) as _i9.Future<_i5.ExamResponseModel>);

  @override
  _i9.Future<_i6.SubjectResponseModel> getSubjectList() => (super.noSuchMethod(
        Invocation.method(
          #getSubjectList,
          [],
        ),
        returnValue: _i9.Future<_i6.SubjectResponseModel>.value(
            _FakeSubjectResponseModel_4(
          this,
          Invocation.method(
            #getSubjectList,
            [],
          ),
        )),
      ) as _i9.Future<_i6.SubjectResponseModel>);

  @override
  _i9.Future<_i7.QuestionResponseModel> getQuestionsByExamId(String? examId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getQuestionsByExamId,
          [examId],
        ),
        returnValue: _i9.Future<_i7.QuestionResponseModel>.value(
            _FakeQuestionResponseModel_5(
          this,
          Invocation.method(
            #getQuestionsByExamId,
            [examId],
          ),
        )),
      ) as _i9.Future<_i7.QuestionResponseModel>);

  @override
  _i9.Future<_i4.AuthResponse> getProfileData() => (super.noSuchMethod(
        Invocation.method(
          #getProfileData,
          [],
        ),
        returnValue: _i9.Future<_i4.AuthResponse>.value(_FakeAuthResponse_2(
          this,
          Invocation.method(
            #getProfileData,
            [],
          ),
        )),
      ) as _i9.Future<_i4.AuthResponse>);

  @override
  _i9.Future<_i4.AuthResponse> editProfile(_i15.UserRequest? body) =>
      (super.noSuchMethod(
        Invocation.method(
          #editProfile,
          [body],
        ),
        returnValue: _i9.Future<_i4.AuthResponse>.value(_FakeAuthResponse_2(
          this,
          Invocation.method(
            #editProfile,
            [body],
          ),
        )),
      ) as _i9.Future<_i4.AuthResponse>);

  @override
  _i9.Future<_i4.AuthResponse> changePassword(
          _i16.ChangePasswordRequest? body) =>
      (super.noSuchMethod(
        Invocation.method(
          #changePassword,
          [body],
        ),
        returnValue: _i9.Future<_i4.AuthResponse>.value(_FakeAuthResponse_2(
          this,
          Invocation.method(
            #changePassword,
            [body],
          ),
        )),
      ) as _i9.Future<_i4.AuthResponse>);
}
