// Mocks generated by Mockito 5.4.4 from annotations
// in online_exam/test/features/auth/data/data_sources/auth_online_datasource_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;

import 'package:dio/dio.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:online_exam/core/networking/api/api_manager.dart' as _i9;
import 'package:online_exam/features/auth/data/models/request/change_password_request.dart'
    as _i17;
import 'package:online_exam/features/auth/data/models/request/ForgetPasswordRequest.dart'
    as _i11;
import 'package:online_exam/features/auth/data/models/request/RegisterRequest.dart'
    as _i15;
import 'package:online_exam/features/auth/data/models/request/ResetPasswordRequest.dart'
    as _i13;
import 'package:online_exam/features/auth/data/models/request/SignInRequest.dart'
    as _i14;
import 'package:online_exam/features/auth/data/models/request/VerifyResetCodeRequest.dart'
    as _i12;
import 'dart:async' as _i9;

import 'package:mockito/mockito.dart' as _i1;
import 'package:online_exam/core/networking/api/api_manager.dart' as _i8;
import 'package:online_exam/features/auth/data/models/request/change_password_request.dart'
    as _i16;
import 'package:online_exam/features/auth/data/models/request/ForgetPasswordRequest.dart'
    as _i10;
import 'package:online_exam/features/auth/data/models/request/RegisterRequest.dart'
    as _i14;
import 'package:online_exam/features/auth/data/models/request/ResetPasswordRequest.dart'
    as _i12;
import 'package:online_exam/features/auth/data/models/request/SignInRequest.dart'
    as _i13;
import 'package:online_exam/features/auth/data/models/request/VerifyResetCodeRequest.dart'
    as _i11;
import 'package:online_exam/features/auth/data/models/response/auth_response_model.dart'
    as _i4;
import 'package:online_exam/features/auth/data/models/response/ForgotPasswordResponse.dart'
    as _i2;
import 'package:online_exam/features/auth/data/models/response/VerifyResetCodeResponse.dart'
    as _i3;
import 'package:online_exam/features/auth/domain/entities/user.dart' as _i16;
import 'package:online_exam/features/auth/domain/entities/user.dart' as _i15;
import 'package:online_exam/features/exam/data/models/response/exam_response_model.dart'
    as _i5;
import 'package:online_exam/features/questions/data/models/question_response_model.dart'
    as _i7;
import 'package:online_exam/features/survey/data/models/subject_response_model.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeForgotPasswordResponse_0 extends _i1.SmartFake
    implements _i2.ForgotPasswordResponse {
  _FakeForgotPasswordResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVerifyResetCodeResponse_1 extends _i1.SmartFake
    implements _i3.VerifyResetCodeResponse {
  _FakeVerifyResetCodeResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuthResponse_2 extends _i1.SmartFake implements _i4.AuthResponse {
  _FakeAuthResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeExamResponseModel_3 extends _i1.SmartFake
    implements _i5.ExamResponseModel {
  _FakeExamResponseModel_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSubjectResponseModel_4 extends _i1.SmartFake
    implements _i6.SubjectResponseModel {
  _FakeSubjectResponseModel_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeQuestionResponseModel_5 extends _i1.SmartFake
    implements _i7.QuestionResponseModel {
  _FakeQuestionResponseModel_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBaseOptions_6 extends _i1.SmartFake implements _i8.BaseOptions {
  _FakeBaseOptions_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHttpClientAdapter_7 extends _i1.SmartFake
    implements _i8.HttpClientAdapter {
  _FakeHttpClientAdapter_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTransformer_8 extends _i1.SmartFake implements _i8.Transformer {
  _FakeTransformer_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInterceptors_9 extends _i1.SmartFake implements _i8.Interceptors {
  _FakeInterceptors_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_10<T1> extends _i1.SmartFake implements _i8.Response<T1> {
  _FakeResponse_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiManager extends _i1.Mock implements _i9.ApiManager {
/// A class which mocks [ApiManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiManager extends _i1.Mock implements _i8.ApiManager {
  MockApiManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i2.ForgotPasswordResponse> forgotPassword(
          _i11.ForgetPasswordRequest? body) =>
  _i9.Future<_i2.ForgotPasswordResponse> forgotPassword(
          _i10.ForgetPasswordRequest? body) =>
      (super.noSuchMethod(
        Invocation.method(
          #forgotPassword,
          [body],
        ),
        returnValue: _i10.Future<_i2.ForgotPasswordResponse>.value(
        returnValue: _i9.Future<_i2.ForgotPasswordResponse>.value(
            _FakeForgotPasswordResponse_0(
          this,
          Invocation.method(
            #forgotPassword,
            [body],
          ),
        )),
      ) as _i10.Future<_i2.ForgotPasswordResponse>);

  @override
  _i10.Future<_i3.VerifyResetCodeResponse> verifyResetCode(
          _i12.VerifyResetCodeRequest? body) =>
      ) as _i9.Future<_i2.ForgotPasswordResponse>);

  @override
  _i9.Future<_i3.VerifyResetCodeResponse> verifyResetCode(
          _i11.VerifyResetCodeRequest? body) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyResetCode,
          [body],
        ),
        returnValue: _i10.Future<_i3.VerifyResetCodeResponse>.value(
        returnValue: _i9.Future<_i3.VerifyResetCodeResponse>.value(
            _FakeVerifyResetCodeResponse_1(
          this,
          Invocation.method(
            #verifyResetCode,
            [body],
          ),
        )),
      ) as _i10.Future<_i3.VerifyResetCodeResponse>);

  @override
  _i10.Future<_i4.AuthResponse> resetPassword(
          _i13.ResetPasswordRequest? body) =>
      ) as _i9.Future<_i3.VerifyResetCodeResponse>);

  @override
  _i9.Future<_i4.AuthResponse> resetPassword(_i12.ResetPasswordRequest? body) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [body],
        ),
        returnValue: _i10.Future<_i4.AuthResponse>.value(_FakeAuthResponse_2(
        returnValue: _i9.Future<_i4.AuthResponse>.value(_FakeAuthResponse_2(
          this,
          Invocation.method(
            #resetPassword,
            [body],
          ),
        )),
      ) as _i10.Future<_i4.AuthResponse>);

  @override
  _i10.Future<_i4.AuthResponse> signIn(_i14.SignInRequest? user) =>
      ) as _i9.Future<_i4.AuthResponse>);

  @override
  _i9.Future<_i4.AuthResponse> signIn(_i13.SignInRequest? user) =>
      (super.noSuchMethod(
        Invocation.method(
          #signIn,
          [user],
        ),
        returnValue: _i10.Future<_i4.AuthResponse>.value(_FakeAuthResponse_2(
        returnValue: _i9.Future<_i4.AuthResponse>.value(_FakeAuthResponse_2(
          this,
          Invocation.method(
            #signIn,
            [user],
          ),
        )),
      ) as _i10.Future<_i4.AuthResponse>);

  @override
  _i10.Future<_i4.AuthResponse> signUp(_i15.RegisterRequest? user) =>
      ) as _i9.Future<_i4.AuthResponse>);

  @override
  _i9.Future<_i4.AuthResponse> signUp(_i14.RegisterRequest? user) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUp,
          [user],
        ),
        returnValue: _i10.Future<_i4.AuthResponse>.value(_FakeAuthResponse_2(
        returnValue: _i9.Future<_i4.AuthResponse>.value(_FakeAuthResponse_2(
          this,
          Invocation.method(
            #signUp,
            [user],
          ),
        )),
      ) as _i10.Future<_i4.AuthResponse>);

  @override
  _i10.Future<_i5.ExamResponseModel> getExamsBySubjectId(String? subjectId) =>
      ) as _i9.Future<_i4.AuthResponse>);

  @override
  _i9.Future<_i5.ExamResponseModel> getExamsBySubjectId(String? subjectId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getExamsBySubjectId,
          [subjectId],
        ),
        returnValue:
            _i10.Future<_i5.ExamResponseModel>.value(_FakeExamResponseModel_3(
            _i9.Future<_i5.ExamResponseModel>.value(_FakeExamResponseModel_3(
          this,
          Invocation.method(
            #getExamsBySubjectId,
            [subjectId],
          ),
        )),
      ) as _i10.Future<_i5.ExamResponseModel>);

  @override
  _i10.Future<_i6.SubjectResponseModel> getSubjectList() => (super.noSuchMethod(
      ) as _i9.Future<_i5.ExamResponseModel>);

  @override
  _i9.Future<_i6.SubjectResponseModel> getSubjectList() => (super.noSuchMethod(
        Invocation.method(
          #getSubjectList,
          [],
        ),
        returnValue: _i10.Future<_i6.SubjectResponseModel>.value(
        returnValue: _i9.Future<_i6.SubjectResponseModel>.value(
            _FakeSubjectResponseModel_4(
          this,
          Invocation.method(
            #getSubjectList,
            [],
          ),
        )),
      ) as _i10.Future<_i6.SubjectResponseModel>);

  @override
  _i10.Future<_i7.QuestionResponseModel> getQuestionsByExamId(String? examId) =>
      ) as _i9.Future<_i6.SubjectResponseModel>);

  @override
  _i9.Future<_i7.QuestionResponseModel> getQuestionsByExamId(String? examId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getQuestionsByExamId,
          [examId],
        ),
        returnValue: _i10.Future<_i7.QuestionResponseModel>.value(
        returnValue: _i9.Future<_i7.QuestionResponseModel>.value(
            _FakeQuestionResponseModel_5(
          this,
          Invocation.method(
            #getQuestionsByExamId,
            [examId],
          ),
        )),
      ) as _i10.Future<_i7.QuestionResponseModel>);

  @override
  _i10.Future<_i4.AuthResponse> getProfileData() => (super.noSuchMethod(
      ) as _i9.Future<_i7.QuestionResponseModel>);

  @override
  _i9.Future<_i4.AuthResponse> getProfileData() => (super.noSuchMethod(
        Invocation.method(
          #getProfileData,
          [],
        ),
        returnValue: _i10.Future<_i4.AuthResponse>.value(_FakeAuthResponse_2(
        returnValue: _i9.Future<_i4.AuthResponse>.value(_FakeAuthResponse_2(
          this,
          Invocation.method(
            #getProfileData,
            [],
          ),
        )),
      ) as _i10.Future<_i4.AuthResponse>);

  @override
  _i10.Future<_i4.AuthResponse> editProfile(_i16.User? body) =>
      ) as _i9.Future<_i4.AuthResponse>);

  @override
  _i9.Future<_i4.AuthResponse> editProfile(_i15.User? body) =>
      (super.noSuchMethod(
        Invocation.method(
          #editProfile,
          [body],
        ),
        returnValue: _i10.Future<_i4.AuthResponse>.value(_FakeAuthResponse_2(
        returnValue: _i9.Future<_i4.AuthResponse>.value(_FakeAuthResponse_2(
          this,
          Invocation.method(
            #editProfile,
            [body],
          ),
        )),
      ) as _i10.Future<_i4.AuthResponse>);

  @override
  _i10.Future<_i4.AuthResponse> changePassword(
          _i17.ChangePasswordRequest? body) =>
      ) as _i9.Future<_i4.AuthResponse>);

  @override
  _i9.Future<_i4.AuthResponse> changePassword(
          _i16.ChangePasswordRequest? body) =>
      (super.noSuchMethod(
        Invocation.method(
          #changePassword,
          [body],
        ),
        returnValue: _i10.Future<_i4.AuthResponse>.value(_FakeAuthResponse_2(
        returnValue: _i9.Future<_i4.AuthResponse>.value(_FakeAuthResponse_2(
          this,
          Invocation.method(
            #changePassword,
            [body],
          ),
        )),
      ) as _i10.Future<_i4.AuthResponse>);
}

/// A class which mocks [Dio].
///
/// See the documentation for Mockito's code generation for more information.
class MockDio extends _i1.Mock implements _i8.Dio {
  MockDio() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.BaseOptions get options => (super.noSuchMethod(
        Invocation.getter(#options),
        returnValue: _FakeBaseOptions_6(
          this,
          Invocation.getter(#options),
        ),
      ) as _i8.BaseOptions);

  @override
  set options(_i8.BaseOptions? _options) => super.noSuchMethod(
        Invocation.setter(
          #options,
          _options,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.HttpClientAdapter get httpClientAdapter => (super.noSuchMethod(
        Invocation.getter(#httpClientAdapter),
        returnValue: _FakeHttpClientAdapter_7(
          this,
          Invocation.getter(#httpClientAdapter),
        ),
      ) as _i8.HttpClientAdapter);

  @override
  set httpClientAdapter(_i8.HttpClientAdapter? _httpClientAdapter) =>
      super.noSuchMethod(
        Invocation.setter(
          #httpClientAdapter,
          _httpClientAdapter,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Transformer get transformer => (super.noSuchMethod(
        Invocation.getter(#transformer),
        returnValue: _FakeTransformer_8(
          this,
          Invocation.getter(#transformer),
        ),
      ) as _i8.Transformer);

  @override
  set transformer(_i8.Transformer? _transformer) => super.noSuchMethod(
        Invocation.setter(
          #transformer,
          _transformer,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Interceptors get interceptors => (super.noSuchMethod(
        Invocation.getter(#interceptors),
        returnValue: _FakeInterceptors_9(
          this,
          Invocation.getter(#interceptors),
        ),
      ) as _i8.Interceptors);

  @override
  void close({bool? force = false}) => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
          {#force: force},
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i10.Future<_i8.Response<T>> head<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i8.Options? options,
    _i8.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #head,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i10.Future<_i8.Response<T>>.value(_FakeResponse_10<T>(
          this,
          Invocation.method(
            #head,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i10.Future<_i8.Response<T>>);

  @override
  _i10.Future<_i8.Response<T>> headUri<T>(
    Uri? uri, {
    Object? data,
    _i8.Options? options,
    _i8.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #headUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i10.Future<_i8.Response<T>>.value(_FakeResponse_10<T>(
          this,
          Invocation.method(
            #headUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i10.Future<_i8.Response<T>>);

  @override
  _i10.Future<_i8.Response<T>> get<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i8.Options? options,
    _i8.CancelToken? cancelToken,
    _i8.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i10.Future<_i8.Response<T>>.value(_FakeResponse_10<T>(
          this,
          Invocation.method(
            #get,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i10.Future<_i8.Response<T>>);

  @override
  _i10.Future<_i8.Response<T>> getUri<T>(
    Uri? uri, {
    Object? data,
    _i8.Options? options,
    _i8.CancelToken? cancelToken,
    _i8.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i10.Future<_i8.Response<T>>.value(_FakeResponse_10<T>(
          this,
          Invocation.method(
            #getUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i10.Future<_i8.Response<T>>);

  @override
  _i10.Future<_i8.Response<T>> post<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i8.Options? options,
    _i8.CancelToken? cancelToken,
    _i8.ProgressCallback? onSendProgress,
    _i8.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i10.Future<_i8.Response<T>>.value(_FakeResponse_10<T>(
          this,
          Invocation.method(
            #post,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i10.Future<_i8.Response<T>>);

  @override
  _i10.Future<_i8.Response<T>> postUri<T>(
    Uri? uri, {
    Object? data,
    _i8.Options? options,
    _i8.CancelToken? cancelToken,
    _i8.ProgressCallback? onSendProgress,
    _i8.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #postUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i10.Future<_i8.Response<T>>.value(_FakeResponse_10<T>(
          this,
          Invocation.method(
            #postUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i10.Future<_i8.Response<T>>);

  @override
  _i10.Future<_i8.Response<T>> put<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i8.Options? options,
    _i8.CancelToken? cancelToken,
    _i8.ProgressCallback? onSendProgress,
    _i8.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i10.Future<_i8.Response<T>>.value(_FakeResponse_10<T>(
          this,
          Invocation.method(
            #put,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i10.Future<_i8.Response<T>>);

  @override
  _i10.Future<_i8.Response<T>> putUri<T>(
    Uri? uri, {
    Object? data,
    _i8.Options? options,
    _i8.CancelToken? cancelToken,
    _i8.ProgressCallback? onSendProgress,
    _i8.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #putUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i10.Future<_i8.Response<T>>.value(_FakeResponse_10<T>(
          this,
          Invocation.method(
            #putUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i10.Future<_i8.Response<T>>);

  @override
  _i10.Future<_i8.Response<T>> patch<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i8.Options? options,
    _i8.CancelToken? cancelToken,
    _i8.ProgressCallback? onSendProgress,
    _i8.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i10.Future<_i8.Response<T>>.value(_FakeResponse_10<T>(
          this,
          Invocation.method(
            #patch,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i10.Future<_i8.Response<T>>);

  @override
  _i10.Future<_i8.Response<T>> patchUri<T>(
    Uri? uri, {
    Object? data,
    _i8.Options? options,
    _i8.CancelToken? cancelToken,
    _i8.ProgressCallback? onSendProgress,
    _i8.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patchUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i10.Future<_i8.Response<T>>.value(_FakeResponse_10<T>(
          this,
          Invocation.method(
            #patchUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i10.Future<_i8.Response<T>>);

  @override
  _i10.Future<_i8.Response<T>> delete<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i8.Options? options,
    _i8.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i10.Future<_i8.Response<T>>.value(_FakeResponse_10<T>(
          this,
          Invocation.method(
            #delete,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i10.Future<_i8.Response<T>>);

  @override
  _i10.Future<_i8.Response<T>> deleteUri<T>(
    Uri? uri, {
    Object? data,
    _i8.Options? options,
    _i8.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i10.Future<_i8.Response<T>>.value(_FakeResponse_10<T>(
          this,
          Invocation.method(
            #deleteUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i10.Future<_i8.Response<T>>);

  @override
  _i10.Future<_i8.Response<dynamic>> download(
    String? urlPath,
    dynamic savePath, {
    _i8.ProgressCallback? onReceiveProgress,
    Map<String, dynamic>? queryParameters,
    _i8.CancelToken? cancelToken,
    bool? deleteOnError = true,
    String? lengthHeader = r'content-length',
    Object? data,
    _i8.Options? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #download,
          [
            urlPath,
            savePath,
          ],
          {
            #onReceiveProgress: onReceiveProgress,
            #queryParameters: queryParameters,
            #cancelToken: cancelToken,
            #deleteOnError: deleteOnError,
            #lengthHeader: lengthHeader,
            #data: data,
            #options: options,
          },
        ),
        returnValue:
            _i10.Future<_i8.Response<dynamic>>.value(_FakeResponse_10<dynamic>(
          this,
          Invocation.method(
            #download,
            [
              urlPath,
              savePath,
            ],
            {
              #onReceiveProgress: onReceiveProgress,
              #queryParameters: queryParameters,
              #cancelToken: cancelToken,
              #deleteOnError: deleteOnError,
              #lengthHeader: lengthHeader,
              #data: data,
              #options: options,
            },
          ),
        )),
      ) as _i10.Future<_i8.Response<dynamic>>);

  @override
  _i10.Future<_i8.Response<dynamic>> downloadUri(
    Uri? uri,
    dynamic savePath, {
    _i8.ProgressCallback? onReceiveProgress,
    _i8.CancelToken? cancelToken,
    bool? deleteOnError = true,
    String? lengthHeader = r'content-length',
    Object? data,
    _i8.Options? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadUri,
          [
            uri,
            savePath,
          ],
          {
            #onReceiveProgress: onReceiveProgress,
            #cancelToken: cancelToken,
            #deleteOnError: deleteOnError,
            #lengthHeader: lengthHeader,
            #data: data,
            #options: options,
          },
        ),
        returnValue:
            _i10.Future<_i8.Response<dynamic>>.value(_FakeResponse_10<dynamic>(
          this,
          Invocation.method(
            #downloadUri,
            [
              uri,
              savePath,
            ],
            {
              #onReceiveProgress: onReceiveProgress,
              #cancelToken: cancelToken,
              #deleteOnError: deleteOnError,
              #lengthHeader: lengthHeader,
              #data: data,
              #options: options,
            },
          ),
        )),
      ) as _i10.Future<_i8.Response<dynamic>>);

  @override
  _i10.Future<_i8.Response<T>> request<T>(
    String? url, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i8.CancelToken? cancelToken,
    _i8.Options? options,
    _i8.ProgressCallback? onSendProgress,
    _i8.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #request,
          [url],
          {
            #data: data,
            #queryParameters: queryParameters,
            #cancelToken: cancelToken,
            #options: options,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i10.Future<_i8.Response<T>>.value(_FakeResponse_10<T>(
          this,
          Invocation.method(
            #request,
            [url],
            {
              #data: data,
              #queryParameters: queryParameters,
              #cancelToken: cancelToken,
              #options: options,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i10.Future<_i8.Response<T>>);

  @override
  _i10.Future<_i8.Response<T>> requestUri<T>(
    Uri? uri, {
    Object? data,
    _i8.CancelToken? cancelToken,
    _i8.Options? options,
    _i8.ProgressCallback? onSendProgress,
    _i8.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestUri,
          [uri],
          {
            #data: data,
            #cancelToken: cancelToken,
            #options: options,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i10.Future<_i8.Response<T>>.value(_FakeResponse_10<T>(
          this,
          Invocation.method(
            #requestUri,
            [uri],
            {
              #data: data,
              #cancelToken: cancelToken,
              #options: options,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i10.Future<_i8.Response<T>>);

  @override
  _i10.Future<_i8.Response<T>> fetch<T>(_i8.RequestOptions? requestOptions) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetch,
          [requestOptions],
        ),
        returnValue: _i10.Future<_i8.Response<T>>.value(_FakeResponse_10<T>(
          this,
          Invocation.method(
            #fetch,
            [requestOptions],
          ),
        )),
      ) as _i10.Future<_i8.Response<T>>);
      ) as _i9.Future<_i4.AuthResponse>);
}
